/*Level-2: Problem 1 - Store Wise Sales Summary
Scenario:
The regional manager wants to analyze total sales generated by each store.
📌 Requirements
1. Display store_name and total sales amount.
2. Calculate total sales using (quantity * list_price * (1 - discount)).
3. Include only completed orders (order_status = 4).
4. Group results by store_name.
5. Sort total sales in descending order.

🛠️ Technical Constraints
- Use INNER JOIN between stores, orders, and order_items tables.
- Use GROUP BY clause.
- Use aggregate functions such as SUM().
- Use WHERE clause for filtering.
- Use ORDER BY clause.

Expectations:
Students must write a grouped query with calculated columns and apply proper filtering.
🎯 Learning Outcome 
Understand GROUP BY, aggregate functions, calculated fields, and filtering grouped data.*/

SELECT 
    s.store_name,
    SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_sales
FROM stores s
INNER JOIN orders o 
    ON s.store_id = o.store_id
INNER JOIN order_items oi 
    ON o.order_id = oi.order_id
WHERE o.order_status = 4
GROUP BY s.store_name
ORDER BY total_sales DESC;
